#Function to generate random samples by inverse CDF method

################ Random samples from exponential distribution #############
  g <- function(x, lambda) {
	rv <-  - 1/lambda * log(1 - x) 
	return (rv)
	}

#Function call - main function .   
  lambda <- 5
  y <- g(runif(1000, min=pexp(-10, rate=lambda), max=pexp(10, rate=lambda)), lambda) 
  


################ Random samples from Cauchy distribution ##################
  cauc <- function(x, sc) {
	rvc <-  sc * tan (pi * (x-0.5)) 
	return (rvc)
	}

#Function call - main function .   
  loc <- 0
  scale <- 2
set.seed(2)
  z <- cauc(runif(1000, min=pcauchy(-10, location = 0, scale =2, lower.tail = TRUE, log.p = FALSE), max=pcauchy (10, location = 0, scale=2, lower.tail = TRUE, log.p = FALSE)), scale) 

#generating the histogram
#generating the histogram
hist(y,prob=TRUE,xlab='X',main='Normal random samples generated by inverse CDF (exponential)')
x11()
hist(z,prob=TRUE,xlab='X',main='CAUCHY')




#######---------------------------------------------------------------
####### chi- square goodness of fit tests.


set.seed(2)
cauchydata <- rcauchy(1000, location = 0, scale = 2)
ChiCauchy <- (sum(z - cauchydata) ^2 )/ sum (cauchydata)
ChiCauchy

set.seed(2)
expdata <- rexp(1000, rate = 5)
ChiExponential <- (sum(y - expdata) ^2)/sum(expdata)
ChiExponential

#########
x11()
qqplot(expdata,y)
abline(0,1)
x11()
qqplot(cauchydata,z)
abline(0,1)